# Generated by Django 5.1 on 2025-03-21 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('category_active', models.BooleanField(default=True)),
                ('category_description', models.CharField(max_length=200)),
                ('category_pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('student_email', models.EmailField(max_length=200, unique=True)),
                ('student_password', models.CharField(max_length=200)),
                ('student_active', models.BooleanField(default=True)),
                ('student_pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhraseCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase_collection_title', models.CharField(max_length=200)),
                ('phrase_collection_pub_date', models.DateTimeField(auto_now_add=True)),
                ('phrase_collection_json', models.JSONField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word_and_phrase.student')),
            ],
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=500)),
                ('phrase_pl', models.CharField(max_length=500)),
                ('phrase_pl_api', models.CharField(max_length=500)),
                ('phrase_pub_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word_and_phrase.category')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word_and_phrase.student')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('word_pl', models.CharField(max_length=200)),
                ('word_pl_api', models.CharField(max_length=200)),
                ('word_pub_date', models.DateTimeField(auto_now_add=True)),
                ('word_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word_and_phrase.category')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word_and_phrase.student')),
            ],
        ),
        migrations.CreateModel(
            name='WordCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_collection_title', models.CharField(max_length=200)),
                ('word_collection_pub_date', models.DateTimeField(auto_now_add=True)),
                ('word_collection_json', models.JSONField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word_and_phrase.student')),
            ],
        ),
    ]
